services:
  backend:
    build: ./backend
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./database
    networks:
      - app-network
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - /Users/nathan/Desktop/tp1_docker:/var/lib/postgresql/data

  httpd:
    build: ./frontend
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
