#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Launch app container
  docker_container:
    name: backend
    image: shqk/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    networks:
      - name: app-network
    env:
      DATABASE_URL: 'postgresql://{{ db_user }}:{{ db_password }}@database:5432/{{ db_name }}'
    ports:
      - '8080:8080'
